
tasks:
  - init: npm install && npm run build
    command: npm run start



vscode:
  extensions:
    - dbaeumer.vscode-eslintintroduction/learn-gitpod/gitpod-yaml)
    - dbaeumer.vscode-eslint# and commit this file to your remote git repository to share the goodness with others.
    - esbenp.prettier-vscode# Learn more from ready-to-use templates: https://www.gitpod.io/docs/introduction/getting-started/quickstart
tasks:
  - init: npm install && npm run build
    command: npm run start
